apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-notification-service
  template:
    metadata:
      labels:
        app: circleguard-notification-service
    spec:
      containers:
      - name: circleguard-notification-service
        image: circleguard-notification-service
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
