apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-file-service
  template:
    metadata:
      labels:
        app: circleguard-file-service
    spec:
      containers:
      - name: file
        image: circleguard-file-service
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"