apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleguard-deployer
  namespace: circleguard-stage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: circleguard-deployer
  namespace: circleguard-stage
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "services", "deployments", "replicasets", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: circleguard-deployer
  namespace: circleguard-stage
subjects:
- kind: ServiceAccount
  name: circleguard-deployer
roleRef:
  kind: Role
  name: circleguard-deployer
  apiGroup: rbac.authorization.k8s.io
