apiVersion: v1
kind: Secret
metadata:
  name: circleguard-secrets-example
  namespace: circleguard-stage
type: Opaque
stringData:
  JWT_SECRET: replace-with-sealed-secret-or-vault-ref
  POSTGRES_PASSWORD: replace-with-secret-manager-value
