apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-promotion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-promotion-service
  template:
    metadata:
      labels:
        app: circleguard-promotion-service
    spec:
      containers:
      - name: circleguard-promotion-service
        image: circleguard-promotion-service
        ports:
        - containerPort: 8088
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
